name: prod
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: composer install

      - name: Run phpcbf
        run: vendor/bin/phpcbf src

      - name: Run tests
        run: vendor/bin/phpunit

